# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [255]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key
g_key = "AIzaSyAcXBr9g-rK3IiIB_Hjk6FSNJoXeq62p38"
url = "https://maps.googleapis.com/maps/api/geocode/json?"
url_find = "https://maps.googleapis.com/maps/api/place/nearbysearch/json" #params for this one
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [256]:
#here we're reading the data frame and dropping any NaN values and pesky weird columns. 
df = pd.read_csv("/Users/jlh/ucb-bel-data-pt-08-2020-u-c/02-Homework/06-Python-APIs/Instructions/starter_code/clean_all_weather_data.csv")
df.columns
df.drop(columns=["Unnamed: 0"], inplace=True)
df.dropna(inplace=True)
df

,city,latitude,longitude,max temp,humidity,cloudiness,wind speeds,country,date
1,clyde river,70.47,-68.59,28.40,92.0,90.0,14.99,CA,1601530562
2,san patricio,19.22,-104.70,78.01,81.0,100.0,4.09,MX,1601530617
3,surt,31.21,16.59,71.69,78.0,0.0,8.86,LY,1601530617
4,bethel,41.37,-73.41,57.22,63.0,1.0,9.17,US,1601530618
5,hermanus,-34.42,19.23,54.03,74.0,100.0,24.45,ZA,1601530618
...,...,...,...,...,...,...,...,...,...
597,chimore,-16.98,-65.13,75.85,61.0,19.0,1.70,BO,1601530472
598,san carlos,9.66,-68.58,71.91,94.0,97.0,6.33,VE,1601530973
599,vostok,46.49,135.88,53.96,60.0,100.0,1.97,RU,1601530768
600,kwinana,-32.25,115.77,68.94,52.0,90.0,18.34,AU,1601530975
601,pyshchug,58.89,45.71,52.12,86.0,90.0,3.98,RU,1601530977

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [257]:
#reviewing code 
#target_city = "Boise, Idaho"


#query_url = ('https://maps.googleapis.com/maps/api/geocode/json?'
 #   'address={0}&key={1}').format(target_city, g_key)
#response = requests.get(query_url).json()
#print(json.dumps(response, indent=4, sort_keys=True))
#we're creating variables so we can plot them for our various heat maps

locations = df[["latitude", "longitude"]].astype(float)
humidity = df["humidity"].astype(float)
cloudiness = df["cloudiness"].astype(float)
windspeeds = df["wind speeds"].astype(float)
max_temp = df["max temp"].astype(float)

In [258]:
#humidity heat map goes first
fig_humid = gmaps.figure()


humid_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=100, point_radius=1)

fig_humid.add_layer(humid_layer)
fig_humid

Figure(layout=FigureLayout(height='420px'))

In [259]:
#cloudy heat map
fig_cloudy = gmaps.figure()


cloudy_layer = gmaps.heatmap_layer(locations, weights=cloudiness, dissipating=False, max_intensity=100, point_radius=1)

fig_cloudy.add_layer(cloudy_layer)
fig_cloudy

Figure(layout=FigureLayout(height='420px'))

In [260]:
#windy
fig_wind_speeds = gmaps.figure()


wind_layer = gmaps.heatmap_layer(locations, weights=windspeeds, dissipating=False, max_intensity=40, point_radius=1)

fig_wind_speeds.add_layer(heat_layer)
fig_wind_speeds

Figure(layout=FigureLayout(height='420px'))

In [220]:
#accidentally doubled up on windy, but spent too much time on this project to delete code
#fig_windy = gmaps.figure()


#windy_layer = gmaps.heatmap_layer(locations, weights=windspeeds, dissipating=False, max_intensity=40, point_radius=1)

#fig_windy.add_layer(windy_layer)
#fig_windy

Figure(layout=FigureLayout(height='420px'))

In [261]:
#max temp
fig_maxtemp = gmaps.figure()


temp_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False, max_intensity=40, point_radius=1)

fig_maxtemp.add_layer(temp_layer)
fig_maxtemp

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [262]:
#we use loc to remove any entries that don't have all of our criteria
df_vacation = df.loc[(df["max temp"] < 80) & \
                     (df["max temp"] > 70) & \
                     (df["wind speeds"] < 10) & \
                     (df["cloudiness"] == 0)]
df_vacation

,city,latitude,longitude,max temp,humidity,cloudiness,wind speeds,country,date
3,surt,31.21,16.59,71.69,78.0,0.0,8.86,LY,1601530617
8,san quintin,30.48,-115.95,78.06,42.0,0.0,5.48,MX,1601530619
43,peabiru,-23.91,-52.34,73.27,51.0,0.0,6.98,BR,1601530633
268,qena,26.16,32.72,77.00,31.0,0.0,3.36,EG,1601530738
355,guerrero negro,27.98,-114.06,78.71,50.0,0.0,6.51,MX,1601530797
378,marsa matruh,31.35,27.25,76.41,64.0,0.0,8.72,EG,1601530818
445,agadez,19.75,10.25,79.50,17.0,0.0,8.48,NE,1601530862
505,sydney,-33.87,151.21,71.49,22.0,0.0,8.05,AU,1601530902
515,suez,29.97,32.53,77.74,71.0,0.0,8.75,EG,1601530688

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [263]:
#we create an empty space for the hotel name we'll later itteraterow to
df_vacation["hotel name"] = ""
df_vacation["hotel name"] = df_vacation["hotel name"].astype(str)
df_vacation.head(8)

<ipython-input-263-2aff70f0f6de>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vacation["hotel name"] = ""
<ipython-input-263-2aff70f0f6de>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vacation["hotel name"] = df_vacation["hotel name"].astype(str)

,city,latitude,longitude,max temp,humidity,cloudiness,wind speeds,country,date,hotel name
3,surt,31.21,16.59,71.69,78.0,0.0,8.86,LY,1601530617,
8,san quintin,30.48,-115.95,78.06,42.0,0.0,5.48,MX,1601530619,
43,peabiru,-23.91,-52.34,73.27,51.0,0.0,6.98,BR,1601530633,
268,qena,26.16,32.72,77.00,31.0,0.0,3.36,EG,1601530738,
355,guerrero negro,27.98,-114.06,78.71,50.0,0.0,6.51,MX,1601530797,
378,marsa matruh,31.35,27.25,76.41,64.0,0.0,8.72,EG,1601530818,
445,agadez,19.75,10.25,79.50,17.0,0.0,8.48,NE,1601530862,
505,sydney,-33.87,151.21,71.49,22.0,0.0,8.05,AU,1601530902,

In [264]:
# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "hotels",
    "keyword": "hotels",
    "key": "AIzaSyAcXBr9g-rK3IiIB_Hjk6FSNJoXeq62p38"
}

# Use the lat/lng we recovered to identify hotels
for index, row in df_vacation.iterrows():
    # get lat, lng from df
    lat = row["latitude"]
    lng = row["longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "hotels" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_hotel = requests.get(base_url, params=params).json()
    #print(json.dumps(name_hotel, indent=4, sort_keys=True))
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)
    try:
        df_vacation.loc[index, "hotels"] = name_hotel["results"][0]["name"]
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

df_vacation

/Users/jlh/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/Users/jlh/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Missing field/result... skipping.

,city,latitude,longitude,max temp,humidity,cloudiness,wind speeds,country,date,hotel name,hotels
3,surt,31.21,16.59,71.69,78.0,0.0,8.86,LY,1601530617,,Sea Hotel
8,san quintin,30.48,-115.95,78.06,42.0,0.0,5.48,MX,1601530619,,Old Mill Hotel
43,peabiru,-23.91,-52.34,73.27,51.0,0.0,6.98,BR,1601530633,,La visa hotel
268,qena,26.16,32.72,77.00,31.0,0.0,3.36,EG,1601530738,,Basma Hotel
355,guerrero negro,27.98,-114.06,78.71,50.0,0.0,6.51,MX,1601530797,,The Halfway Inn
378,marsa matruh,31.35,27.25,76.41,64.0,0.0,8.72,EG,1601530818,,Beau Site
445,agadez,19.75,10.25,79.50,17.0,0.0,8.48,NE,1601530862,,NaN
505,sydney,-33.87,151.21,71.49,22.0,0.0,8.05,AU,1601530902,,"Shangri-La Hotel, Sydney"
515,suez,29.97,32.53,77.74,71.0,0.0,8.75,EG,1601530688,,Ù†Ø§Ø¯Ù‰ Ø§Ù„Ø¨Ø­Ø§Ø±Ø© Ø§Ù„Ø¯ÙˆÙ„Ù‰ Ø¨Ø§Ù„Ø³ÙˆÙŠØ³ - International Se...

In [265]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{hotel name}</dd>
<dt>City</dt><dd>{city}</dd>
<dt>Country</dt><dd>{country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in df_vacation.iterrows()]
locations_n = df_vacation[["latitude", "longitude"]].astype(float)

In [266]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations_n)

figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wiâ€¦